### ISSUE TITLE
improvements in the ontology viewer

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#77]
A few things would be quite helpful (I'll take the example of [adm:statementScore](http://purl.bdrc.io/ontology/admin/statementScore) where all these are visible):
- [ ] display the `rdfs:comment` property, it's a very important one
- [ ] `Rdf Type` should be `Type`
- [ ] There should be no space before columns: `Rdf Type:`, not `Rdf Type :` (only French typography uses space here)
- [ ] `URI` is not very interesting, it could be removed (the URI already appears in the web browser)
- [ ] the literals should be printed using the same format as turtle: `Label: "score"@en`, not `Label: score`
- [ ] classes, individuals, etc. should also be printed using the usual format: , `Range: xsd:integer` not `Range : integer`, and there should be html links, for instance `xsd:integer` should be a link to `https://www.w3.org/2001/XMLSchema#integer` (which in this case is not interesting, but in most cases is)

**Comment by MarcAgate** [comment]
Fixed as of commit d87f3cd

**Comment by eroux** [comment]
The links in http://purl.bdrc.io/ontology/admin/statementScore are still wrong (some links go to invalid addresses like adm:StatementAnnotationBody

**Comment by MarcAgate** [comment]
Fixed as of commit 9576e72 (also added styled display of labels and comments in class view)

**Comment by eroux** [comment]
A space is still missing after "Comment:", otherwise it's good, thanks!

**Comment by MarcAgate** [comment]
Fixed as of commit da7eaba
